name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
