services:
  digital_library_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  digital_library_app:
    image: digital_library_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - digital_library_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@digital_library_database:5432/app_db

volumes:
  pgdata:
